name: wikapi
description: Wikipedia apis wrapper
version: 0.3.0
repository: https://github.com/gilcu2/wikapi.git

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  http: ^0.13.5
  tuple: ^2.0.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
